### ISSUE TITLE
Deploy tests are not being triggered

### ISSUE THREAD

**Issue by octonato** [lagom/lagom-samples#103]
It seems that the deploy stage is not being triggered in Travis. 

Here is an example of a build from a PR that should have triggered the deployment.

https://travis-ci.com/lagom/lagom-samples/builds/130444259

Not PR is NOT sent from a fork and is targeting on the main branches (ie: 1.5.x)

**Comment by TimMoore** [comment]
This started with the change in #88. I can't find clear documentation on this, but it looks like encrypted variables must not be available when it evaluates conditional build stages.
