### ISSUE TITLE
Branch protection rules

### ISSUE THREAD

**Issue by TimMoore** [lagom/lagom-samples#108]
There aren't any branch protection rules configured in this repository: https://github.com/lagom/lagom-samples/settings/branches

This could lead to accidental merges of code that hasn't passed the Travis CI or CLA validator checks.

What should they be?

**Comment by octonato** [comment]
this is done

**Comment by octonato** [comment]
Reopen it. I forget that we have `.github/settings.yml` configured for this repo but for some reason, it's not quick in.

**Comment by octonato** [comment]
this is now fixed by #114
