### ISSUE TITLE
Need Sample for grpc with Maven 

### ISSUE THREAD

**Issue by venkateshzifo** [lagom/lagom-samples#177]
### Lagom Version (1.2.x / 1.3.x / etc)
1.6.3

### API (Scala / Java / Neither / Both)
Java

**Comment by ignasi35** [comment]
Related to https://github.com/akka/akka-grpc/issues/1103

**Comment by ignasi35** [comment]
Hi @venkateshzifo, I've put together a couple of commits in https://github.com/ignasi35/lagom-samples/commits/lagom-grpc-maven. You can test the application using:

```
cd grpc-example/grpc-example-java
sbt test
```

or with the new maven build:

```
cd grpc-example/grpc-example-java
mvn clean verify -e
```

I've added you as co-author on the commit and I'll push that code as a PR.

**Comment by venkateshzifo** [comment]
When i do mvn lagom:runAll I am getting below error when i hit http://localhost:9000/proxy/grpc-hello/Steve

{"name":"io.grpc.StatusRuntimeException: UNAVAILABLE: io exception","detail":"io.grpc.StatusRuntimeException: UNAVAILABLE: io exception\r\n\tat io.grpc.Status.asRuntimeException(Status.java:533)\r\n\tat akka.grpc.internal.UnaryCallAdapter.onClose(UnaryCallAdapter.scala:40)\r\n\tat io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)\r\n\tat io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)\r\n\tat io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)\r\n\tat io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)\r\n\tat io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)\r\n\tat io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)\r\n\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\r\n\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)\r\n\tat java.base/java.lang.Thread.run(Thread.java:832)\r\nCaused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: ZSLP012/172.16.4.3:11011\r\nCaused by: java.net.ConnectException: Connection refused: no further information\r\n\tat java.base/sun.nio.ch.Net.pollConnect(Native Method)\r\n\tat java.base/sun.nio.ch.Net.pollConnectNow(Net.java:589)\r\n\tat java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:839)\r\n\tat io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)\r\n\tat io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)\r\n\tat io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)\r\n\tat io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)\r\n\tat io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)\r\n\tat io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)\r\n\tat io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\r\n\tat io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\r\n\tat io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\r\n\tat java.base/java.lang.Thread.run(Thread.java:832)\r\n"}

Please help me with this

**Comment by ignasi35** [comment]
hi @venkateshzifo, this sounds like a OS-level PROXY setup is affecting your dev mode.

See this discussion (https://github.com/lagom/lagom/issues/1575) for more details on how to solve th issue.
