### ISSUE TITLE
Add docs wrt `management` port name

### ISSUE THREAD

**Issue by ignasi35** [lagom/lagom-samples#19]
Shopping cart `prod-application.conf` references port by name `management` it'd be good to add a comment linking to the YAML file.

https://github.com/lagom/shopping-cart-scala/blob/e30b41723922ed635a8c072ea138262147a69cea/shopping-cart-impl/src/main/resources/prod-application.conf#L38

**Comment by TimMoore** [comment]
IIUC, with recent changes to Akka Management from @jroper, we would be able to entirely remove the explicit references to the Akka Management port and rely on default behavior. It should be rare to need to override the default.

It isn't totally clear to me whether the changes in 1.0.0 are enough, or if we would need some more the more recent changes to be released.

**Comment by jroper** [comment]
With https://github.com/akka/akka-management/pull/541, which will be part of Akka Management 1.0.1, there is no longer any need to mention the Akka management port anywhere when using kubernetes api discovery, in any configuration file or descriptor, for bootstrapping purposes. Furthermore, if it is declared in the container port spec, the name of the port can be anything, with the default cluster bootstrapping configuration, the ports are not looked at. The name only matters if you configure cluster bootstrap to use a particular port. By default now, it does a lookup with no port name specified, and the kubernetes-api lookup in that case will return all the pods that match the selector, regardless of what ports they declare, returning the pods that match with no port. Cluster bootstrap then, when it gets back no port, defaults to the configured Akka management port number.

That however doesn't mean that it shouldn't be mentioned - the port is needed for the health check, and this can either be configured by mentioning it by number in the health check port configuration, or by creating a named container port and referring to it by name from the health checks.

**Comment by TimMoore** [comment]
Already resolved in https://github.com/lagom/shopping-cart-scala/pull/22
