### ISSUE TITLE
EOL the merged-in sample repos

### ISSUE THREAD

**Issue by dwijnand** [lagom/lagom-samples#36]
* Update README and/or open an issue and/or update the repo description about the move
* Archive the repo

- [x] https://github.com/lagom/shopping-cart-scala
- [x] https://github.com/lagom/shopping-cart-java
- [x] https://github.com/lagom/online-auction-scala (dropped `1.5.x` and archived)
- [x] https://github.com/lagom/online-auction-java (dropped `1.5.x` and archived)
- [x] https://github.com/lagom/lagom-java-maven-chirper-example (dropped `1.5.x` and archived)
- [x] https://github.com/lagom/lagom-java-sbt-chirper-example (dropped `1.5.x` and archived)
- [x] https://github.com/lagom/lagom-java-grpc-example (archived, branch `1.5.x` is the only one)
- [x] https://github.com/lagom/lagom-scala-grpc-example  (archived, branch `1.5.x` is the only one)
- [x] https://github.com/lagom/lagom-java-openshift-smoketests (#37) (archived, branch `1.5.x` is the only one)
- [x] https://github.com/lagom/lagom-scala-openshift-smoketests (#37) (archived, branch `1.5.x` is the only one)

**Comment by octonato** [comment]
I'm waiting until the migrated projects are ready in example code service and tech hub.

Online auction and chirper can be archived already. I will do it today.

**Comment by ignasi35** [comment]
All repos on the list (except shopping-cart) are now archived.
