### ISSUE TITLE
openshift-smoketests repos?

### ISSUE THREAD

**Issue by dwijnand** [lagom/lagom-samples#37]
* https://github.com/lagom/lagom-java-openshift-smoketests, and
* https://github.com/lagom/lagom-scala-openshift-smoketests

Are these going to be merged into this repo and the functionality moved to the shopping cart apps, @lagom/core?

**Comment by dwijnand** [comment]
#16 related

**Comment by ignasi35** [comment]
I think the plan was to archive the `smoketests`.

**Comment by ignasi35** [comment]
Smoketest repos are now archived. Ci-based deployment will be implemented using `shopping cart` sample apps.
