### ISSUE TITLE
Add README section with community samples and recipes

### ISSUE THREAD

**Issue by octonato** [lagom/lagom-samples#9]

**Comment by octonato** [comment]
@ihostage / @silver-soule, you have probably seen that we've archived [lagom/lagom-recipes](https://github.com/lagom/lagom-recipes).

To my knowledge, you are the only external contributors to the recipes. So, we would like to invite you to add links to the samples and recipes you have created on the README file on this new samples project. 

The goal is to link to your own repos. You don't need to send PRs to add recipes to this repo. Our goal is to reduce the maintaince on our side and unlock you. You can let your repo evolve the way you prefer. As long as the linked samples stay relevant we will keep the link here.

**Comment by ihostage** [comment]
@renatocaval Thanks! 👍 
I will try to do it soon.

**Comment by ignasi35** [comment]
Done in #35

**Comment by silver-soule** [comment]
@renatocaval Thanks for the update! I'll try to add  mine in a bit as well .
